# Generated by Django 6.0.3 on 2026-05-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_gender', models.CharField(max_length=10)),
                ('user_age', models.IntegerField()),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_password', models.CharField(max_length=128)),
                ('user_active', models.BooleanField(default=True)),
            ],
        ),
    ]
