# Generated by Django 6.0.3 on 2026-05-27 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visitor_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_name', models.CharField(max_length=100)),
                ('position_code', models.CharField(max_length=10)),
                ('position_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Time_Schedule',
            fields=[
                ('time_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_range', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=200, unique=True)),
                ('club_district', models.CharField(max_length=100)),
                ('club_location', models.CharField(max_length=100)),
                ('club_weight', models.IntegerField(default=10, null=True)),
                ('club_logo', models.ImageField(upload_to='club_logo/')),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('club_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_app.user')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.club')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('error', 'Error')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_app.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_order_id', models.CharField(max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('signature_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failure', 'Failure')], default='Pending', max_length=10)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_card_name', models.CharField(max_length=20)),
                ('player_rating', models.IntegerField(default=50)),
                ('player_strong_foot', models.CharField(max_length=10)),
                ('player_weight', models.IntegerField()),
                ('player_height', models.IntegerField()),
                ('player_power', models.IntegerField()),
                ('player_district', models.CharField(max_length=100)),
                ('player_location', models.CharField(max_length=100)),
                ('player_image', models.ImageField(upload_to='players/')),
                ('player_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.club')),
                ('player_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visitor_app.user')),
                ('player_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.position')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_date', models.DateField()),
                ('match_time', models.CharField(blank=True, max_length=100, null=True)),
                ('match_started', models.BooleanField(default=False)),
                ('match_finished', models.BooleanField(default=False)),
                ('match_away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='user_app.club')),
                ('match_home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='user_app.club')),
                ('away_squad', models.ManyToManyField(blank=True, related_name='away_squad', to='user_app.player')),
                ('away_subs', models.ManyToManyField(blank=True, related_name='away_subs', to='user_app.player')),
                ('home_squad', models.ManyToManyField(blank=True, related_name='home_squad', to='user_app.player')),
                ('home_subs', models.ManyToManyField(blank=True, related_name='home_subs', to='user_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('result_home_team', models.IntegerField(default=0)),
                ('result_away_team', models.IntegerField(default=0)),
                ('result_video', models.FileField(blank=True, null=True, upload_to='match_videos/')),
                ('result_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_app.match')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('for_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.player')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.result')),
            ],
        ),
        migrations.CreateModel(
            name='Assist',
            fields=[
                ('assist_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('for_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.player')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.result')),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('save_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('for_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.player')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.result')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(blank=True, max_length=100, null=True)),
                ('t_date', models.DateField()),
                ('t_host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.club')),
            ],
        ),
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('turf_id', models.AutoField(primary_key=True, serialize=False)),
                ('turf_name', models.CharField(max_length=200)),
                ('turf_rate', models.IntegerField()),
                ('turf_district', models.CharField(max_length=100)),
                ('turf_location', models.CharField(max_length=100)),
                ('turf_image', models.ImageField(upload_to='turfs/')),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('turf_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitor_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='match_turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.turf'),
        ),
        migrations.AddField(
            model_name='club',
            name='club_home_ground',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_app.turf'),
        ),
        migrations.AddField(
            model_name='booking',
            name='turf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.turf'),
        ),
        migrations.CreateModel(
            name='Turf_time_map',
            fields=[
                ('tt_id', models.AutoField(primary_key=True, serialize=False)),
                ('tt_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.time_schedule')),
                ('tt_turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.turf')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.turf_time_map'),
        ),
        migrations.CreateModel(
            name='T_club_map',
            fields=[
                ('t_c_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_c_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.club')),
                ('t_c_tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.tournament')),
            ],
            options={
                'unique_together': {('t_c_tournament', 't_c_club')},
            },
        ),
    ]
