# Generated by Django 6.0.5 on 2026-07-13 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_knockout',
            field=models.BooleanField(default=False, help_text='True for knockout rounds'),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.IntegerField(default=1, help_text='Round number in tournament (1=group stage, 2=quarters, 3=semis, 4=final)'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='user_app.tournament'),
        ),
        migrations.AddField(
            model_name='t_club_map',
            name='drawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='t_club_map',
            name='goals_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='t_club_map',
            name='goals_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='t_club_map',
            name='group_name',
            field=models.CharField(blank=True, help_text='A, B, C, etc.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='t_club_map',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='t_club_map',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='t_club_map',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='t_club_map',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='t_club_map',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='t_club_map',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='t_club_map',
            name='won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('league', 'Round Robin (League)'), ('knockout', 'Knockout (Single Elimination)'), ('hybrid', 'Group Stage + Knockout')], default='hybrid', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Tournament is currently running'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Tournament has finished'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(default=16, help_text='Maximum number of teams allowed'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_pool',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee required to join tournament', max_digits=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams_per_group',
            field=models.IntegerField(default=4, help_text='Teams per group in hybrid format'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams_qualifying',
            field=models.IntegerField(default=2, help_text='Teams qualifying from each group'),
        ),
        migrations.CreateModel(
            name='TournamentPayment',
            fields=[
                ('tp_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_order_id', models.CharField(max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('signature_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failure', 'Failure')], default='Pending', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.t_club_map')),
            ],
        ),
    ]
