# Generated by Django 6.0.5 on 2026-07-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_match_is_knockout_match_round_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bracket_position',
            field=models.IntegerField(default=0, help_text='Position in knockout bracket (0-indexed)'),
        ),
    ]
