# Generated by Django 6.0.5 on 2026-07-20 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_match_bracket_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='user_app.club'),
        ),
    ]
