# Generated by Django 6.0.5 on 2026-07-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_match_match_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_squad_selected',
            field=models.BooleanField(default=False, help_text='True when away team squad has been selected'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_squad_selected',
            field=models.BooleanField(default=False, help_text='True when home team squad has been selected'),
        ),
        migrations.AddField(
            model_name='match',
            name='squad_size',
            field=models.PositiveSmallIntegerField(default=5, help_text='Number of starting players for this match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='squad_size',
            field=models.PositiveSmallIntegerField(choices=[(5, '5-a-side'), (7, '7-a-side'), (9, '9-a-side'), (11, '11-a-side'), (12, '12-a-side')], default=5, help_text='Number of starting players per team in tournament matches'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='squads_selected',
            field=models.BooleanField(default=False, help_text='True when all tournament match squads have been configured'),
        ),
    ]
