# Generated by Django 6.0.5 on 2026-09-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_match_away_squad_selected_match_home_squad_selected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
