# Generated by Django 6.0.5 on 2026-09-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_match_match_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_duration',
            field=models.PositiveIntegerField(default=5400, help_text='Total match duration in seconds'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_elapsed_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Seconds already elapsed before the current timer run'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='match_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_finished',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
