# Generated by Django 6.0.5 on 2026-09-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_match_match_duration_match_match_elapsed_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_finished',
            field=models.BooleanField(default=False),
        ),
    ]
